version: '3'

services:
  postgres:
    container_name: cap-postgres
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-apqc_r721}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - cap
    restart: unless-stopped

networks:
  cap:
    driver: bridge

volumes:
  postgres:
