FROM node:10-alpine

RUN yarn global add pm2

RUN mkdir /root/app

ARG NODE_ENV=production
ARG PORT=4000
ARG JWT_SECERT=capadmin_auth_jwt_secret
ARG JWT_EXPIRE_IN=90d
ARG TOKEN_STARTUPS_API=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1ODM0NDM4OTksInN1YiI6ImFjY2VzcyJ9.YiROK6kFyIZNLmFtHqHDNf_cxyUShXixMdh-5N1Q6vY
ARG NEO4J_URI=bolt://host:7687
ARG NEO4J_USER=neo4j
ARG NEO4J_PASSWORD=s3cr3t
ARG DATABASE_TYPE=postgres
ARG DATABASE_HOST
ARG DATABASE_PORT
ARG DATABASE_NAME
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG GRAPH_DATABASE_TYPE=AGENS_GRAPH
ARG GRAPH_DATABASE_USER=agens
ARG GRAPH_DATABASE_PASSWORD
ARG GRAPH_DATABASE_HOST=localhost
ARG GRAPH_DATABASE_PORT=5432
ARG GRAPH_DATABASE_NAME=capdata

ENV NODE_ENV=$NODE_ENV PORT=$PORT JWT_SECERT=$JWT_SECERT JWT_EXPIRE_IN=$JWT_EXPIRE_IN TOKEN_STARTUPS_API=$TOKEN_STARTUPS_API NEO4J_URI=$NEO4J_URI NEO4J_USER=$NEO4J_USER NEO4J_PASSWORD=$NEO4J_PASSWORD DATABASE_TYPE=$DATABASE_TYPE DATABASE_HOST=$DATABASE_HOST DATABASE_PORT=$DATABASE_PORT DATABASE_NAME=$DATABASE_NAME DATABASE_USERNAME=$DATABASE_USERNAME DATABASE_PASSWORD=$DATABASE_PASSWORD GRAPH_DATABASE_TYPE=$GRAPH_DATABASE_TYPE GRAPH_DATABASE_USER=$GRAPH_DATABASE_USER GRAPH_DATABASE_PASSWORD=$GRAPH_DATABASE_PASSWORD GRAPH_DATABASE_HOST=$GRAPH_DATABASE_HOST GRAPH_DATABASE_PORT=$GRAPH_DATABASE_PORT GRAPH_DATABASE_NAME=$GRAPH_DATABASE_NAME

ADD . /root/app

WORKDIR /root/app

RUN yarn global add pegjs
RUN yarn --pure-lockfile
RUN yarn cache clean

CMD [ "pm2-runtime", "start", "ecosystem.config.js"]
